{"uuid": "96d533a6-3587-4e7e-8de2-7d519189954c", "children": ["8db6ceb8-8ddb-430c-a2d2-2f210f667fcb"], "befores": [{"name": "_UnitTestCase__pytest_class_setup", "status": "passed", "start": 1590992096951, "stop": 1590992109427}], "afters": [{"name": "_UnitTestCase__pytest_class_setup::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\_pytest\\unittest.py\", line 105, in fixture\n    teardown()\n  File \"C:\\Users\\17327\\PycharmProjects\\yunhe\\scripts\\systemManageScript\\test_user_manage.py\", line 19, in tearDownClass\n    GetDriver().quit_driver()\n  File \"C:\\Users\\17327\\PycharmProjects\\yunhe\\base\\get_driver.py\", line 19, in quit_driver\n    cls.driver.quit()\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 203, in quit\n    RemoteWebDriver.quit(self)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 698, in quit\n    self.execute(Command.QUIT)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\urllib3\\request.py\", line 76, in request\n    method, url, fields=fields, headers=headers, **urlopen_kw\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\urllib3\\request.py\", line 97, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\urllib3\\poolmanager.py\", line 336, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\urllib3\\connectionpool.py\", line 765, in urlopen\n    **response_kw\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\urllib3\\connectionpool.py\", line 765, in urlopen\n    **response_kw\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\urllib3\\connectionpool.py\", line 677, in urlopen\n    chunked=chunked,\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\urllib3\\connectionpool.py\", line 392, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\http\\client.py\", line 1229, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\http\\client.py\", line 1275, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\http\\client.py\", line 1224, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\http\\client.py\", line 1016, in _send_output\n    self.send(msg)\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\http\\client.py\", line 956, in send\n    self.connect()\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\urllib3\\connection.py\", line 187, in connect\n    conn = self._new_conn()\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\urllib3\\connection.py\", line 160, in _new_conn\n    (self._dns_host, self.port), self.timeout, **extra_kw\n  File \"c:\\users\\17327\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\urllib3\\util\\connection.py\", line 74, in create_connection\n    sock.connect(sa)\n"}, "start": 1590992119546, "stop": 1590992125644}], "start": 1590992096951, "stop": 1590992125660}